changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - chore
        - refactor
    - title: 🏗️ Infrastructure
      labels:
        - ci
        - infrastructure
    - title: Other Changes
      labels:
        - "*"
