apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: offly
build:
  artifacts:
    - image: bananaops/offly
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
          VITE_API_URL: "/api/v1"
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
deploy:
  helm:
    releases:
      - name: offly
        chartPath: helm/offly
        namespace: offly
        createNamespace: true
        setValues:
          mongodb.enabled: true
          ingress.enabled: true
          ingress.hosts[0].host: offly.dev.energy-pool.eu
          ingress.hosts[0].paths[0].path: /
          ingress.hosts[0].paths[0].pathType: ImplementationSpecific
          ingress.className: traefik-internal
          
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_bananaops_offly}}"
          image.tag: "{{.IMAGE_TAG_bananaops_offly}}@{{.IMAGE_DIGEST_bananaops_offly}}"
