version: "2"

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  exclude-dirs:
    - proto
