// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: absence/v1/absence.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AbsenceService_CreateAbsence_FullMethodName = "/absence.v1.AbsenceService/CreateAbsence"
	AbsenceService_GetAbsences_FullMethodName   = "/absence.v1.AbsenceService/GetAbsences"
	AbsenceService_UpdateAbsence_FullMethodName = "/absence.v1.AbsenceService/UpdateAbsence"
	AbsenceService_DeleteAbsence_FullMethodName = "/absence.v1.AbsenceService/DeleteAbsence"
)

// AbsenceServiceClient is the client API for AbsenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service de gestion des absences
type AbsenceServiceClient interface {
	CreateAbsence(ctx context.Context, in *CreateAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error)
	GetAbsences(ctx context.Context, in *GetAbsencesRequest, opts ...grpc.CallOption) (*GetAbsencesResponse, error)
	UpdateAbsence(ctx context.Context, in *UpdateAbsenceRequest, opts ...grpc.CallOption) (*UpdateAbsenceResponse, error)
	DeleteAbsence(ctx context.Context, in *DeleteAbsenceRequest, opts ...grpc.CallOption) (*DeleteAbsenceResponse, error)
}

type absenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAbsenceServiceClient(cc grpc.ClientConnInterface) AbsenceServiceClient {
	return &absenceServiceClient{cc}
}

func (c *absenceServiceClient) CreateAbsence(ctx context.Context, in *CreateAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_CreateAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) GetAbsences(ctx context.Context, in *GetAbsencesRequest, opts ...grpc.CallOption) (*GetAbsencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAbsencesResponse)
	err := c.cc.Invoke(ctx, AbsenceService_GetAbsences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) UpdateAbsence(ctx context.Context, in *UpdateAbsenceRequest, opts ...grpc.CallOption) (*UpdateAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_UpdateAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) DeleteAbsence(ctx context.Context, in *DeleteAbsenceRequest, opts ...grpc.CallOption) (*DeleteAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_DeleteAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbsenceServiceServer is the server API for AbsenceService service.
// All implementations must embed UnimplementedAbsenceServiceServer
// for forward compatibility.
//
// Service de gestion des absences
type AbsenceServiceServer interface {
	CreateAbsence(context.Context, *CreateAbsenceRequest) (*CreateAbsenceResponse, error)
	GetAbsences(context.Context, *GetAbsencesRequest) (*GetAbsencesResponse, error)
	UpdateAbsence(context.Context, *UpdateAbsenceRequest) (*UpdateAbsenceResponse, error)
	DeleteAbsence(context.Context, *DeleteAbsenceRequest) (*DeleteAbsenceResponse, error)
	mustEmbedUnimplementedAbsenceServiceServer()
}

// UnimplementedAbsenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAbsenceServiceServer struct{}

func (UnimplementedAbsenceServiceServer) CreateAbsence(context.Context, *CreateAbsenceRequest) (*CreateAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) GetAbsences(context.Context, *GetAbsencesRequest) (*GetAbsencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbsences not implemented")
}
func (UnimplementedAbsenceServiceServer) UpdateAbsence(context.Context, *UpdateAbsenceRequest) (*UpdateAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) DeleteAbsence(context.Context, *DeleteAbsenceRequest) (*DeleteAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) mustEmbedUnimplementedAbsenceServiceServer() {}
func (UnimplementedAbsenceServiceServer) testEmbeddedByValue()                        {}

// UnsafeAbsenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbsenceServiceServer will
// result in compilation errors.
type UnsafeAbsenceServiceServer interface {
	mustEmbedUnimplementedAbsenceServiceServer()
}

func RegisterAbsenceServiceServer(s grpc.ServiceRegistrar, srv AbsenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedAbsenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AbsenceService_ServiceDesc, srv)
}

func _AbsenceService_CreateAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).CreateAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_CreateAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).CreateAbsence(ctx, req.(*CreateAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_GetAbsences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbsencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).GetAbsences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_GetAbsences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).GetAbsences(ctx, req.(*GetAbsencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_UpdateAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).UpdateAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_UpdateAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).UpdateAbsence(ctx, req.(*UpdateAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_DeleteAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).DeleteAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_DeleteAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).DeleteAbsence(ctx, req.(*DeleteAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AbsenceService_ServiceDesc is the grpc.ServiceDesc for AbsenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AbsenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "absence.v1.AbsenceService",
	HandlerType: (*AbsenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAbsence",
			Handler:    _AbsenceService_CreateAbsence_Handler,
		},
		{
			MethodName: "GetAbsences",
			Handler:    _AbsenceService_GetAbsences_Handler,
		},
		{
			MethodName: "UpdateAbsence",
			Handler:    _AbsenceService_UpdateAbsence_Handler,
		},
		{
			MethodName: "DeleteAbsence",
			Handler:    _AbsenceService_DeleteAbsence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "absence/v1/absence.proto",
}

const (
	UserService_CreateUser_FullMethodName             = "/absence.v1.UserService/CreateUser"
	UserService_GetUsers_FullMethodName               = "/absence.v1.UserService/GetUsers"
	UserService_AssignUserToDepartment_FullMethodName = "/absence.v1.UserService/AssignUserToDepartment"
	UserService_AssignUserToTeam_FullMethodName       = "/absence.v1.UserService/AssignUserToTeam"
	UserService_UpdateUser_FullMethodName             = "/absence.v1.UserService/UpdateUser"
	UserService_DeleteUser_FullMethodName             = "/absence.v1.UserService/DeleteUser"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service de gestion des utilisateurs
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	AssignUserToDepartment(ctx context.Context, in *AssignUserToDepartmentRequest, opts ...grpc.CallOption) (*AssignUserToDepartmentResponse, error)
	AssignUserToTeam(ctx context.Context, in *AssignUserToTeamRequest, opts ...grpc.CallOption) (*AssignUserToTeamResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, UserService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AssignUserToDepartment(ctx context.Context, in *AssignUserToDepartmentRequest, opts ...grpc.CallOption) (*AssignUserToDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignUserToDepartmentResponse)
	err := c.cc.Invoke(ctx, UserService_AssignUserToDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AssignUserToTeam(ctx context.Context, in *AssignUserToTeamRequest, opts ...grpc.CallOption) (*AssignUserToTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignUserToTeamResponse)
	err := c.cc.Invoke(ctx, UserService_AssignUserToTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// Service de gestion des utilisateurs
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	AssignUserToDepartment(context.Context, *AssignUserToDepartmentRequest) (*AssignUserToDepartmentResponse, error)
	AssignUserToTeam(context.Context, *AssignUserToTeamRequest) (*AssignUserToTeamResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUserServiceServer) AssignUserToDepartment(context.Context, *AssignUserToDepartmentRequest) (*AssignUserToDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignUserToDepartment not implemented")
}
func (UnimplementedUserServiceServer) AssignUserToTeam(context.Context, *AssignUserToTeamRequest) (*AssignUserToTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignUserToTeam not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AssignUserToDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserToDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AssignUserToDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AssignUserToDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AssignUserToDepartment(ctx, req.(*AssignUserToDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AssignUserToTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserToTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AssignUserToTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AssignUserToTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AssignUserToTeam(ctx, req.(*AssignUserToTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "absence.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
		{
			MethodName: "AssignUserToDepartment",
			Handler:    _UserService_AssignUserToDepartment_Handler,
		},
		{
			MethodName: "AssignUserToTeam",
			Handler:    _UserService_AssignUserToTeam_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "absence/v1/absence.proto",
}

const (
	OrganizationService_CreateDepartment_FullMethodName = "/absence.v1.OrganizationService/CreateDepartment"
	OrganizationService_GetDepartments_FullMethodName   = "/absence.v1.OrganizationService/GetDepartments"
	OrganizationService_CreateTeam_FullMethodName       = "/absence.v1.OrganizationService/CreateTeam"
	OrganizationService_GetTeams_FullMethodName         = "/absence.v1.OrganizationService/GetTeams"
	OrganizationService_UpdateDepartment_FullMethodName = "/absence.v1.OrganizationService/UpdateDepartment"
	OrganizationService_DeleteDepartment_FullMethodName = "/absence.v1.OrganizationService/DeleteDepartment"
	OrganizationService_UpdateTeam_FullMethodName       = "/absence.v1.OrganizationService/UpdateTeam"
	OrganizationService_DeleteTeam_FullMethodName       = "/absence.v1.OrganizationService/DeleteTeam"
)

// OrganizationServiceClient is the client API for OrganizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service de gestion des départements et équipes
type OrganizationServiceClient interface {
	CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...grpc.CallOption) (*CreateDepartmentResponse, error)
	GetDepartments(ctx context.Context, in *GetDepartmentsRequest, opts ...grpc.CallOption) (*GetDepartmentsResponse, error)
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
	GetTeams(ctx context.Context, in *GetTeamsRequest, opts ...grpc.CallOption) (*GetTeamsResponse, error)
	UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...grpc.CallOption) (*UpdateDepartmentResponse, error)
	DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*DeleteDepartmentResponse, error)
	UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error)
	DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
}

type organizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizationServiceClient(cc grpc.ClientConnInterface) OrganizationServiceClient {
	return &organizationServiceClient{cc}
}

func (c *organizationServiceClient) CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...grpc.CallOption) (*CreateDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDepartmentResponse)
	err := c.cc.Invoke(ctx, OrganizationService_CreateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) GetDepartments(ctx context.Context, in *GetDepartmentsRequest, opts ...grpc.CallOption) (*GetDepartmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentsResponse)
	err := c.cc.Invoke(ctx, OrganizationService_GetDepartments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamResponse)
	err := c.cc.Invoke(ctx, OrganizationService_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) GetTeams(ctx context.Context, in *GetTeamsRequest, opts ...grpc.CallOption) (*GetTeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamsResponse)
	err := c.cc.Invoke(ctx, OrganizationService_GetTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...grpc.CallOption) (*UpdateDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDepartmentResponse)
	err := c.cc.Invoke(ctx, OrganizationService_UpdateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*DeleteDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDepartmentResponse)
	err := c.cc.Invoke(ctx, OrganizationService_DeleteDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTeamResponse)
	err := c.cc.Invoke(ctx, OrganizationService_UpdateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTeamResponse)
	err := c.cc.Invoke(ctx, OrganizationService_DeleteTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationServiceServer is the server API for OrganizationService service.
// All implementations must embed UnimplementedOrganizationServiceServer
// for forward compatibility.
//
// Service de gestion des départements et équipes
type OrganizationServiceServer interface {
	CreateDepartment(context.Context, *CreateDepartmentRequest) (*CreateDepartmentResponse, error)
	GetDepartments(context.Context, *GetDepartmentsRequest) (*GetDepartmentsResponse, error)
	CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error)
	GetTeams(context.Context, *GetTeamsRequest) (*GetTeamsResponse, error)
	UpdateDepartment(context.Context, *UpdateDepartmentRequest) (*UpdateDepartmentResponse, error)
	DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DeleteDepartmentResponse, error)
	UpdateTeam(context.Context, *UpdateTeamRequest) (*UpdateTeamResponse, error)
	DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error)
	mustEmbedUnimplementedOrganizationServiceServer()
}

// UnimplementedOrganizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrganizationServiceServer struct{}

func (UnimplementedOrganizationServiceServer) CreateDepartment(context.Context, *CreateDepartmentRequest) (*CreateDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDepartment not implemented")
}
func (UnimplementedOrganizationServiceServer) GetDepartments(context.Context, *GetDepartmentsRequest) (*GetDepartmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartments not implemented")
}
func (UnimplementedOrganizationServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedOrganizationServiceServer) GetTeams(context.Context, *GetTeamsRequest) (*GetTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeams not implemented")
}
func (UnimplementedOrganizationServiceServer) UpdateDepartment(context.Context, *UpdateDepartmentRequest) (*UpdateDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartment not implemented")
}
func (UnimplementedOrganizationServiceServer) DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DeleteDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartment not implemented")
}
func (UnimplementedOrganizationServiceServer) UpdateTeam(context.Context, *UpdateTeamRequest) (*UpdateTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (UnimplementedOrganizationServiceServer) DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (UnimplementedOrganizationServiceServer) mustEmbedUnimplementedOrganizationServiceServer() {}
func (UnimplementedOrganizationServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrganizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrganizationServiceServer will
// result in compilation errors.
type UnsafeOrganizationServiceServer interface {
	mustEmbedUnimplementedOrganizationServiceServer()
}

func RegisterOrganizationServiceServer(s grpc.ServiceRegistrar, srv OrganizationServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrganizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrganizationService_ServiceDesc, srv)
}

func _OrganizationService_CreateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).CreateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_CreateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).CreateDepartment(ctx, req.(*CreateDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_GetDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).GetDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_GetDepartments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).GetDepartments(ctx, req.(*GetDepartmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_GetTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).GetTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_GetTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).GetTeams(ctx, req.(*GetTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_UpdateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).UpdateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_UpdateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).UpdateDepartment(ctx, req.(*UpdateDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_DeleteDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).DeleteDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_DeleteDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).DeleteDepartment(ctx, req.(*DeleteDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_UpdateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).UpdateTeam(ctx, req.(*UpdateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_DeleteTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).DeleteTeam(ctx, req.(*DeleteTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrganizationService_ServiceDesc is the grpc.ServiceDesc for OrganizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrganizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "absence.v1.OrganizationService",
	HandlerType: (*OrganizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDepartment",
			Handler:    _OrganizationService_CreateDepartment_Handler,
		},
		{
			MethodName: "GetDepartments",
			Handler:    _OrganizationService_GetDepartments_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _OrganizationService_CreateTeam_Handler,
		},
		{
			MethodName: "GetTeams",
			Handler:    _OrganizationService_GetTeams_Handler,
		},
		{
			MethodName: "UpdateDepartment",
			Handler:    _OrganizationService_UpdateDepartment_Handler,
		},
		{
			MethodName: "DeleteDepartment",
			Handler:    _OrganizationService_DeleteDepartment_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _OrganizationService_UpdateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _OrganizationService_DeleteTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "absence/v1/absence.proto",
}

const (
	HolidayService_CreateHoliday_FullMethodName  = "/absence.v1.HolidayService/CreateHoliday"
	HolidayService_GetHolidays_FullMethodName    = "/absence.v1.HolidayService/GetHolidays"
	HolidayService_UpdateHoliday_FullMethodName  = "/absence.v1.HolidayService/UpdateHoliday"
	HolidayService_DeleteHoliday_FullMethodName  = "/absence.v1.HolidayService/DeleteHoliday"
	HolidayService_ImportHolidays_FullMethodName = "/absence.v1.HolidayService/ImportHolidays"
)

// HolidayServiceClient is the client API for HolidayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service de gestion des jours fériés
type HolidayServiceClient interface {
	CreateHoliday(ctx context.Context, in *CreateHolidayRequest, opts ...grpc.CallOption) (*CreateHolidayResponse, error)
	GetHolidays(ctx context.Context, in *GetHolidaysRequest, opts ...grpc.CallOption) (*GetHolidaysResponse, error)
	UpdateHoliday(ctx context.Context, in *UpdateHolidayRequest, opts ...grpc.CallOption) (*UpdateHolidayResponse, error)
	DeleteHoliday(ctx context.Context, in *DeleteHolidayRequest, opts ...grpc.CallOption) (*DeleteHolidayResponse, error)
	ImportHolidays(ctx context.Context, in *ImportHolidaysRequest, opts ...grpc.CallOption) (*ImportHolidaysResponse, error)
}

type holidayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHolidayServiceClient(cc grpc.ClientConnInterface) HolidayServiceClient {
	return &holidayServiceClient{cc}
}

func (c *holidayServiceClient) CreateHoliday(ctx context.Context, in *CreateHolidayRequest, opts ...grpc.CallOption) (*CreateHolidayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHolidayResponse)
	err := c.cc.Invoke(ctx, HolidayService_CreateHoliday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holidayServiceClient) GetHolidays(ctx context.Context, in *GetHolidaysRequest, opts ...grpc.CallOption) (*GetHolidaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHolidaysResponse)
	err := c.cc.Invoke(ctx, HolidayService_GetHolidays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holidayServiceClient) UpdateHoliday(ctx context.Context, in *UpdateHolidayRequest, opts ...grpc.CallOption) (*UpdateHolidayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHolidayResponse)
	err := c.cc.Invoke(ctx, HolidayService_UpdateHoliday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holidayServiceClient) DeleteHoliday(ctx context.Context, in *DeleteHolidayRequest, opts ...grpc.CallOption) (*DeleteHolidayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHolidayResponse)
	err := c.cc.Invoke(ctx, HolidayService_DeleteHoliday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holidayServiceClient) ImportHolidays(ctx context.Context, in *ImportHolidaysRequest, opts ...grpc.CallOption) (*ImportHolidaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportHolidaysResponse)
	err := c.cc.Invoke(ctx, HolidayService_ImportHolidays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HolidayServiceServer is the server API for HolidayService service.
// All implementations must embed UnimplementedHolidayServiceServer
// for forward compatibility.
//
// Service de gestion des jours fériés
type HolidayServiceServer interface {
	CreateHoliday(context.Context, *CreateHolidayRequest) (*CreateHolidayResponse, error)
	GetHolidays(context.Context, *GetHolidaysRequest) (*GetHolidaysResponse, error)
	UpdateHoliday(context.Context, *UpdateHolidayRequest) (*UpdateHolidayResponse, error)
	DeleteHoliday(context.Context, *DeleteHolidayRequest) (*DeleteHolidayResponse, error)
	ImportHolidays(context.Context, *ImportHolidaysRequest) (*ImportHolidaysResponse, error)
	mustEmbedUnimplementedHolidayServiceServer()
}

// UnimplementedHolidayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHolidayServiceServer struct{}

func (UnimplementedHolidayServiceServer) CreateHoliday(context.Context, *CreateHolidayRequest) (*CreateHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHoliday not implemented")
}
func (UnimplementedHolidayServiceServer) GetHolidays(context.Context, *GetHolidaysRequest) (*GetHolidaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHolidays not implemented")
}
func (UnimplementedHolidayServiceServer) UpdateHoliday(context.Context, *UpdateHolidayRequest) (*UpdateHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHoliday not implemented")
}
func (UnimplementedHolidayServiceServer) DeleteHoliday(context.Context, *DeleteHolidayRequest) (*DeleteHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHoliday not implemented")
}
func (UnimplementedHolidayServiceServer) ImportHolidays(context.Context, *ImportHolidaysRequest) (*ImportHolidaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportHolidays not implemented")
}
func (UnimplementedHolidayServiceServer) mustEmbedUnimplementedHolidayServiceServer() {}
func (UnimplementedHolidayServiceServer) testEmbeddedByValue()                        {}

// UnsafeHolidayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HolidayServiceServer will
// result in compilation errors.
type UnsafeHolidayServiceServer interface {
	mustEmbedUnimplementedHolidayServiceServer()
}

func RegisterHolidayServiceServer(s grpc.ServiceRegistrar, srv HolidayServiceServer) {
	// If the following call pancis, it indicates UnimplementedHolidayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HolidayService_ServiceDesc, srv)
}

func _HolidayService_CreateHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HolidayServiceServer).CreateHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HolidayService_CreateHoliday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HolidayServiceServer).CreateHoliday(ctx, req.(*CreateHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HolidayService_GetHolidays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHolidaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HolidayServiceServer).GetHolidays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HolidayService_GetHolidays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HolidayServiceServer).GetHolidays(ctx, req.(*GetHolidaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HolidayService_UpdateHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HolidayServiceServer).UpdateHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HolidayService_UpdateHoliday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HolidayServiceServer).UpdateHoliday(ctx, req.(*UpdateHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HolidayService_DeleteHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HolidayServiceServer).DeleteHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HolidayService_DeleteHoliday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HolidayServiceServer).DeleteHoliday(ctx, req.(*DeleteHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HolidayService_ImportHolidays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportHolidaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HolidayServiceServer).ImportHolidays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HolidayService_ImportHolidays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HolidayServiceServer).ImportHolidays(ctx, req.(*ImportHolidaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HolidayService_ServiceDesc is the grpc.ServiceDesc for HolidayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HolidayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "absence.v1.HolidayService",
	HandlerType: (*HolidayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHoliday",
			Handler:    _HolidayService_CreateHoliday_Handler,
		},
		{
			MethodName: "GetHolidays",
			Handler:    _HolidayService_GetHolidays_Handler,
		},
		{
			MethodName: "UpdateHoliday",
			Handler:    _HolidayService_UpdateHoliday_Handler,
		},
		{
			MethodName: "DeleteHoliday",
			Handler:    _HolidayService_DeleteHoliday_Handler,
		},
		{
			MethodName: "ImportHolidays",
			Handler:    _HolidayService_ImportHolidays_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "absence/v1/absence.proto",
}
