// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: absence/v1/absence.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core types
type Absence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TeamName      string                 `protobuf:"bytes,7,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Absence) Reset() {
	*x = Absence{}
	mi := &file_absence_v1_absence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Absence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Absence) ProtoMessage() {}

func (x *Absence) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Absence.ProtoReflect.Descriptor instead.
func (*Absence) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{0}
}

func (x *Absence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Absence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Absence) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Absence) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Absence) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Absence) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Absence) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,5,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	JobProfile    string                 `protobuf:"bytes,8,opt,name=job_profile,json=jobProfile,proto3" json:"job_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_absence_v1_absence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *User) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *User) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetJobProfile() string {
	if x != nil {
		return x.JobProfile
	}
	return ""
}

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_absence_v1_absence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{2}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_absence_v1_absence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{3}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type Holiday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	mi := &file_absence_v1_absence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{4}
}

func (x *Holiday) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Holiday) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Holiday) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holiday) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Holiday) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

// Absence messages
type CreateAbsenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	TeamName      string                 `protobuf:"bytes,5,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAbsenceRequest) Reset() {
	*x = CreateAbsenceRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAbsenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAbsenceRequest) ProtoMessage() {}

func (x *CreateAbsenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAbsenceRequest.ProtoReflect.Descriptor instead.
func (*CreateAbsenceRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAbsenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAbsenceRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateAbsenceRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CreateAbsenceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateAbsenceRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

type CreateAbsenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Absence       *Absence               `protobuf:"bytes,1,opt,name=absence,proto3" json:"absence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAbsenceResponse) Reset() {
	*x = CreateAbsenceResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAbsenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAbsenceResponse) ProtoMessage() {}

func (x *CreateAbsenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAbsenceResponse.ProtoReflect.Descriptor instead.
func (*CreateAbsenceResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAbsenceResponse) GetAbsence() *Absence {
	if x != nil {
		return x.Absence
	}
	return nil
}

type GetAbsencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbsencesRequest) Reset() {
	*x = GetAbsencesRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbsencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbsencesRequest) ProtoMessage() {}

func (x *GetAbsencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbsencesRequest.ProtoReflect.Descriptor instead.
func (*GetAbsencesRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{7}
}

func (x *GetAbsencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAbsencesRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetAbsencesRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetAbsencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Absences      []*Absence             `protobuf:"bytes,1,rep,name=absences,proto3" json:"absences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbsencesResponse) Reset() {
	*x = GetAbsencesResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbsencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbsencesResponse) ProtoMessage() {}

func (x *GetAbsencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbsencesResponse.ProtoReflect.Descriptor instead.
func (*GetAbsencesResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{8}
}

func (x *GetAbsencesResponse) GetAbsences() []*Absence {
	if x != nil {
		return x.Absences
	}
	return nil
}

type UpdateAbsenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAbsenceRequest) Reset() {
	*x = UpdateAbsenceRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAbsenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAbsenceRequest) ProtoMessage() {}

func (x *UpdateAbsenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAbsenceRequest.ProtoReflect.Descriptor instead.
func (*UpdateAbsenceRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAbsenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAbsenceRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateAbsenceRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateAbsenceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateAbsenceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAbsenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Absence       *Absence               `protobuf:"bytes,1,opt,name=absence,proto3" json:"absence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAbsenceResponse) Reset() {
	*x = UpdateAbsenceResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAbsenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAbsenceResponse) ProtoMessage() {}

func (x *UpdateAbsenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAbsenceResponse.ProtoReflect.Descriptor instead.
func (*UpdateAbsenceResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAbsenceResponse) GetAbsence() *Absence {
	if x != nil {
		return x.Absence
	}
	return nil
}

type DeleteAbsenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAbsenceRequest) Reset() {
	*x = DeleteAbsenceRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAbsenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAbsenceRequest) ProtoMessage() {}

func (x *DeleteAbsenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAbsenceRequest.ProtoReflect.Descriptor instead.
func (*DeleteAbsenceRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAbsenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAbsenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAbsenceResponse) Reset() {
	*x = DeleteAbsenceResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAbsenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAbsenceResponse) ProtoMessage() {}

func (x *DeleteAbsenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAbsenceResponse.ProtoReflect.Descriptor instead.
func (*DeleteAbsenceResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAbsenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// User messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{15}
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AssignUserToDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToDepartmentRequest) Reset() {
	*x = AssignUserToDepartmentRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToDepartmentRequest) ProtoMessage() {}

func (x *AssignUserToDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToDepartmentRequest.ProtoReflect.Descriptor instead.
func (*AssignUserToDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{17}
}

func (x *AssignUserToDepartmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignUserToDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type AssignUserToDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToDepartmentResponse) Reset() {
	*x = AssignUserToDepartmentResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToDepartmentResponse) ProtoMessage() {}

func (x *AssignUserToDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToDepartmentResponse.ProtoReflect.Descriptor instead.
func (*AssignUserToDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{18}
}

func (x *AssignUserToDepartmentResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AssignUserToTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToTeamRequest) Reset() {
	*x = AssignUserToTeamRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToTeamRequest) ProtoMessage() {}

func (x *AssignUserToTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToTeamRequest.ProtoReflect.Descriptor instead.
func (*AssignUserToTeamRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{19}
}

func (x *AssignUserToTeamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignUserToTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type AssignUserToTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserToTeamResponse) Reset() {
	*x = AssignUserToTeamResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserToTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserToTeamResponse) ProtoMessage() {}

func (x *AssignUserToTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserToTeamResponse.ProtoReflect.Descriptor instead.
func (*AssignUserToTeamResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{20}
}

func (x *AssignUserToTeamResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateUserRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Department messages
type CreateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{25}
}

func (x *CreateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentResponse) Reset() {
	*x = CreateDepartmentResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentResponse) ProtoMessage() {}

func (x *CreateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*CreateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{26}
}

func (x *CreateDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type GetDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentsRequest) Reset() {
	*x = GetDepartmentsRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentsRequest) ProtoMessage() {}

func (x *GetDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{27}
}

type GetDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*Department          `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentsResponse) Reset() {
	*x = GetDepartmentsResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentsResponse) ProtoMessage() {}

func (x *GetDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{28}
}

func (x *GetDepartmentsResponse) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

type UpdateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentResponse) Reset() {
	*x = UpdateDepartmentResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentResponse) ProtoMessage() {}

func (x *UpdateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentResponse) Reset() {
	*x = DeleteDepartmentResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentResponse) ProtoMessage() {}

func (x *DeleteDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteDepartmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Team messages
type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{33}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{34}
}

func (x *CreateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsRequest) Reset() {
	*x = GetTeamsRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsRequest) ProtoMessage() {}

func (x *GetTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsRequest.ProtoReflect.Descriptor instead.
func (*GetTeamsRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{35}
}

func (x *GetTeamsRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type GetTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsResponse) Reset() {
	*x = GetTeamsResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsResponse) ProtoMessage() {}

func (x *GetTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsResponse.ProtoReflect.Descriptor instead.
func (*GetTeamsResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{36}
}

func (x *GetTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type UpdateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTeamRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type UpdateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamResponse) Reset() {
	*x = UpdateTeamResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamResponse) ProtoMessage() {}

func (x *UpdateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{38}
}

func (x *UpdateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{39}
}

func (x *DeleteTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{40}
}

func (x *DeleteTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Holiday messages
type CreateHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHolidayRequest) Reset() {
	*x = CreateHolidayRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHolidayRequest) ProtoMessage() {}

func (x *CreateHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHolidayRequest.ProtoReflect.Descriptor instead.
func (*CreateHolidayRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{41}
}

func (x *CreateHolidayRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateHolidayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHolidayRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateHolidayRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type CreateHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holiday       *Holiday               `protobuf:"bytes,1,opt,name=holiday,proto3" json:"holiday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHolidayResponse) Reset() {
	*x = CreateHolidayResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHolidayResponse) ProtoMessage() {}

func (x *CreateHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHolidayResponse.ProtoReflect.Descriptor instead.
func (*CreateHolidayResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{42}
}

func (x *CreateHolidayResponse) GetHoliday() *Holiday {
	if x != nil {
		return x.Holiday
	}
	return nil
}

type GetHolidaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHolidaysRequest) Reset() {
	*x = GetHolidaysRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHolidaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHolidaysRequest) ProtoMessage() {}

func (x *GetHolidaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHolidaysRequest.ProtoReflect.Descriptor instead.
func (*GetHolidaysRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{43}
}

func (x *GetHolidaysRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetHolidaysRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetHolidaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holidays      []*Holiday             `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHolidaysResponse) Reset() {
	*x = GetHolidaysResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHolidaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHolidaysResponse) ProtoMessage() {}

func (x *GetHolidaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHolidaysResponse.ProtoReflect.Descriptor instead.
func (*GetHolidaysResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{44}
}

func (x *GetHolidaysResponse) GetHolidays() []*Holiday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type UpdateHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHolidayRequest) Reset() {
	*x = UpdateHolidayRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHolidayRequest) ProtoMessage() {}

func (x *UpdateHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHolidayRequest.ProtoReflect.Descriptor instead.
func (*UpdateHolidayRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{45}
}

func (x *UpdateHolidayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateHolidayRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateHolidayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateHolidayRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateHolidayRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type UpdateHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holiday       *Holiday               `protobuf:"bytes,1,opt,name=holiday,proto3" json:"holiday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHolidayResponse) Reset() {
	*x = UpdateHolidayResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHolidayResponse) ProtoMessage() {}

func (x *UpdateHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHolidayResponse.ProtoReflect.Descriptor instead.
func (*UpdateHolidayResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{46}
}

func (x *UpdateHolidayResponse) GetHoliday() *Holiday {
	if x != nil {
		return x.Holiday
	}
	return nil
}

type DeleteHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHolidayRequest) Reset() {
	*x = DeleteHolidayRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHolidayRequest) ProtoMessage() {}

func (x *DeleteHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHolidayRequest.ProtoReflect.Descriptor instead.
func (*DeleteHolidayRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{47}
}

func (x *DeleteHolidayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHolidayResponse) Reset() {
	*x = DeleteHolidayResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHolidayResponse) ProtoMessage() {}

func (x *DeleteHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHolidayResponse.ProtoReflect.Descriptor instead.
func (*DeleteHolidayResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{48}
}

func (x *DeleteHolidayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ImportHolidaysRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Holidays      []*CreateHolidayRequest `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportHolidaysRequest) Reset() {
	*x = ImportHolidaysRequest{}
	mi := &file_absence_v1_absence_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportHolidaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHolidaysRequest) ProtoMessage() {}

func (x *ImportHolidaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHolidaysRequest.ProtoReflect.Descriptor instead.
func (*ImportHolidaysRequest) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{49}
}

func (x *ImportHolidaysRequest) GetHolidays() []*CreateHolidayRequest {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type ImportHolidaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImportedCount int32                  `protobuf:"varint,1,opt,name=imported_count,json=importedCount,proto3" json:"imported_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportHolidaysResponse) Reset() {
	*x = ImportHolidaysResponse{}
	mi := &file_absence_v1_absence_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportHolidaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHolidaysResponse) ProtoMessage() {}

func (x *ImportHolidaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_absence_v1_absence_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHolidaysResponse.ProtoReflect.Descriptor instead.
func (*ImportHolidaysResponse) Descriptor() ([]byte, []int) {
	return file_absence_v1_absence_proto_rawDescGZIP(), []int{50}
}

func (x *ImportHolidaysResponse) GetImportedCount() int32 {
	if x != nil {
		return x.ImportedCount
	}
	return 0
}

var File_absence_v1_absence_proto protoreflect.FileDescriptor

const file_absence_v1_absence_proto_rawDesc = "" +
	"\n" +
	"\x18absence/v1/absence.proto\x12\n" +
	"absence.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\aAbsence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tteam_name\x18\a \x01(\tR\bteamName\"\xcf\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\tR\fdepartmentId\x12\x17\n" +
	"\ateam_id\x18\x05 \x01(\tR\x06teamId\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x1f\n" +
	"\vjob_profile\x18\b \x01(\tR\n" +
	"jobProfile\"0\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\tR\fdepartmentId\"o\n" +
	"\aHoliday\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\"\xd6\x01\n" +
	"\x14CreateAbsenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1b\n" +
	"\tteam_name\x18\x05 \x01(\tR\bteamName\"F\n" +
	"\x15CreateAbsenceResponse\x12-\n" +
	"\aabsence\x18\x01 \x01(\v2\x13.absence.v1.AbsenceR\aabsence\"\x9f\x01\n" +
	"\x12GetAbsencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"F\n" +
	"\x13GetAbsencesResponse\x12/\n" +
	"\babsences\x18\x01 \x03(\v2\x13.absence.v1.AbsenceR\babsences\"\xc8\x01\n" +
	"\x14UpdateAbsenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"F\n" +
	"\x15UpdateAbsenceResponse\x12-\n" +
	"\aabsence\x18\x01 \x01(\v2\x13.absence.v1.AbsenceR\aabsence\"&\n" +
	"\x14DeleteAbsenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteAbsenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\":\n" +
	"\x12CreateUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.absence.v1.UserR\x04user\"\x11\n" +
	"\x0fGetUsersRequest\":\n" +
	"\x10GetUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.absence.v1.UserR\x05users\"]\n" +
	"\x1dAssignUserToDepartmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\"F\n" +
	"\x1eAssignUserToDepartmentResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.absence.v1.UserR\x04user\"K\n" +
	"\x17AssignUserToTeamRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"@\n" +
	"\x18AssignUserToTeamResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.absence.v1.UserR\x04user\"}\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\":\n" +
	"\x12UpdateUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.absence.v1.UserR\x04user\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x17CreateDepartmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x18CreateDepartmentResponse\x126\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x16.absence.v1.DepartmentR\n" +
	"department\"\x17\n" +
	"\x15GetDepartmentsRequest\"R\n" +
	"\x16GetDepartmentsResponse\x128\n" +
	"\vdepartments\x18\x01 \x03(\v2\x16.absence.v1.DepartmentR\vdepartments\"=\n" +
	"\x17UpdateDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"R\n" +
	"\x18UpdateDepartmentResponse\x126\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x16.absence.v1.DepartmentR\n" +
	"department\")\n" +
	"\x17DeleteDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteDepartmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\":\n" +
	"\x12CreateTeamResponse\x12$\n" +
	"\x04team\x18\x01 \x01(\v2\x10.absence.v1.TeamR\x04team\"6\n" +
	"\x0fGetTeamsRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\":\n" +
	"\x10GetTeamsResponse\x12&\n" +
	"\x05teams\x18\x01 \x03(\v2\x10.absence.v1.TeamR\x05teams\"\\\n" +
	"\x11UpdateTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\tR\fdepartmentId\":\n" +
	"\x12UpdateTeamResponse\x12$\n" +
	"\x04team\x18\x01 \x01(\v2\x10.absence.v1.TeamR\x04team\"#\n" +
	"\x11DeleteTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteTeamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\x14CreateHolidayRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\"F\n" +
	"\x15CreateHolidayResponse\x12-\n" +
	"\aholiday\x18\x01 \x01(\v2\x13.absence.v1.HolidayR\aholiday\"B\n" +
	"\x12GetHolidaysRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"F\n" +
	"\x13GetHolidaysResponse\x12/\n" +
	"\bholidays\x18\x01 \x03(\v2\x13.absence.v1.HolidayR\bholidays\"|\n" +
	"\x14UpdateHolidayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\"F\n" +
	"\x15UpdateHolidayResponse\x12-\n" +
	"\aholiday\x18\x01 \x01(\v2\x13.absence.v1.HolidayR\aholiday\"&\n" +
	"\x14DeleteHolidayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteHolidayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x15ImportHolidaysRequest\x12<\n" +
	"\bholidays\x18\x01 \x03(\v2 .absence.v1.CreateHolidayRequestR\bholidays\"?\n" +
	"\x16ImportHolidaysResponse\x12%\n" +
	"\x0eimported_count\x18\x01 \x01(\x05R\rimportedCount2\xda\x03\n" +
	"\x0eAbsenceService\x12q\n" +
	"\rCreateAbsence\x12 .absence.v1.CreateAbsenceRequest\x1a!.absence.v1.CreateAbsenceResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/absences\x12h\n" +
	"\vGetAbsences\x12\x1e.absence.v1.GetAbsencesRequest\x1a\x1f.absence.v1.GetAbsencesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/absences\x12v\n" +
	"\rUpdateAbsence\x12 .absence.v1.UpdateAbsenceRequest\x1a!.absence.v1.UpdateAbsenceResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/absences/{id}\x12s\n" +
	"\rDeleteAbsence\x12 .absence.v1.DeleteAbsenceRequest\x1a!.absence.v1.DeleteAbsenceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/absences/{id}2\xd1\x05\n" +
	"\vUserService\x12e\n" +
	"\n" +
	"CreateUser\x12\x1d.absence.v1.CreateUserRequest\x1a\x1e.absence.v1.CreateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12\\\n" +
	"\bGetUsers\x12\x1b.absence.v1.GetUsersRequest\x1a\x1c.absence.v1.GetUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12\x9e\x01\n" +
	"\x16AssignUserToDepartment\x12).absence.v1.AssignUserToDepartmentRequest\x1a*.absence.v1.AssignUserToDepartmentResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/users/{user_id}/department\x12\x86\x01\n" +
	"\x10AssignUserToTeam\x12#.absence.v1.AssignUserToTeamRequest\x1a$.absence.v1.AssignUserToTeamResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/users/{user_id}/team\x12j\n" +
	"\n" +
	"UpdateUser\x12\x1d.absence.v1.UpdateUserRequest\x1a\x1e.absence.v1.UpdateUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/users/{id}\x12g\n" +
	"\n" +
	"DeleteUser\x12\x1d.absence.v1.DeleteUserRequest\x1a\x1e.absence.v1.DeleteUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}2\xaa\a\n" +
	"\x13OrganizationService\x12}\n" +
	"\x10CreateDepartment\x12#.absence.v1.CreateDepartmentRequest\x1a$.absence.v1.CreateDepartmentResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/departments\x12t\n" +
	"\x0eGetDepartments\x12!.absence.v1.GetDepartmentsRequest\x1a\".absence.v1.GetDepartmentsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/departments\x12e\n" +
	"\n" +
	"CreateTeam\x12\x1d.absence.v1.CreateTeamRequest\x1a\x1e.absence.v1.CreateTeamResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/teams\x12\\\n" +
	"\bGetTeams\x12\x1b.absence.v1.GetTeamsRequest\x1a\x1c.absence.v1.GetTeamsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/teams\x12\x82\x01\n" +
	"\x10UpdateDepartment\x12#.absence.v1.UpdateDepartmentRequest\x1a$.absence.v1.UpdateDepartmentResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/departments/{id}\x12\x7f\n" +
	"\x10DeleteDepartment\x12#.absence.v1.DeleteDepartmentRequest\x1a$.absence.v1.DeleteDepartmentResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/departments/{id}\x12j\n" +
	"\n" +
	"UpdateTeam\x12\x1d.absence.v1.UpdateTeamRequest\x1a\x1e.absence.v1.UpdateTeamResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/teams/{id}\x12g\n" +
	"\n" +
	"DeleteTeam\x12\x1d.absence.v1.DeleteTeamRequest\x1a\x1e.absence.v1.DeleteTeamResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/teams/{id}2\xd7\x04\n" +
	"\x0eHolidayService\x12q\n" +
	"\rCreateHoliday\x12 .absence.v1.CreateHolidayRequest\x1a!.absence.v1.CreateHolidayResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/holidays\x12h\n" +
	"\vGetHolidays\x12\x1e.absence.v1.GetHolidaysRequest\x1a\x1f.absence.v1.GetHolidaysResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/holidays\x12v\n" +
	"\rUpdateHoliday\x12 .absence.v1.UpdateHolidayRequest\x1a!.absence.v1.UpdateHolidayResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/holidays/{id}\x12s\n" +
	"\rDeleteHoliday\x12 .absence.v1.DeleteHolidayRequest\x1a!.absence.v1.DeleteHolidayResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/holidays/{id}\x12{\n" +
	"\x0eImportHolidays\x12!.absence.v1.ImportHolidaysRequest\x1a\".absence.v1.ImportHolidaysResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/holidays/importB%Z#absence-management/proto/absence/v1b\x06proto3"

var (
	file_absence_v1_absence_proto_rawDescOnce sync.Once
	file_absence_v1_absence_proto_rawDescData []byte
)

func file_absence_v1_absence_proto_rawDescGZIP() []byte {
	file_absence_v1_absence_proto_rawDescOnce.Do(func() {
		file_absence_v1_absence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_absence_v1_absence_proto_rawDesc), len(file_absence_v1_absence_proto_rawDesc)))
	})
	return file_absence_v1_absence_proto_rawDescData
}

var file_absence_v1_absence_proto_msgTypes = make([]protoimpl.MessageInfo, 51)
var file_absence_v1_absence_proto_goTypes = []any{
	(*Absence)(nil),                        // 0: absence.v1.Absence
	(*User)(nil),                           // 1: absence.v1.User
	(*Department)(nil),                     // 2: absence.v1.Department
	(*Team)(nil),                           // 3: absence.v1.Team
	(*Holiday)(nil),                        // 4: absence.v1.Holiday
	(*CreateAbsenceRequest)(nil),           // 5: absence.v1.CreateAbsenceRequest
	(*CreateAbsenceResponse)(nil),          // 6: absence.v1.CreateAbsenceResponse
	(*GetAbsencesRequest)(nil),             // 7: absence.v1.GetAbsencesRequest
	(*GetAbsencesResponse)(nil),            // 8: absence.v1.GetAbsencesResponse
	(*UpdateAbsenceRequest)(nil),           // 9: absence.v1.UpdateAbsenceRequest
	(*UpdateAbsenceResponse)(nil),          // 10: absence.v1.UpdateAbsenceResponse
	(*DeleteAbsenceRequest)(nil),           // 11: absence.v1.DeleteAbsenceRequest
	(*DeleteAbsenceResponse)(nil),          // 12: absence.v1.DeleteAbsenceResponse
	(*CreateUserRequest)(nil),              // 13: absence.v1.CreateUserRequest
	(*CreateUserResponse)(nil),             // 14: absence.v1.CreateUserResponse
	(*GetUsersRequest)(nil),                // 15: absence.v1.GetUsersRequest
	(*GetUsersResponse)(nil),               // 16: absence.v1.GetUsersResponse
	(*AssignUserToDepartmentRequest)(nil),  // 17: absence.v1.AssignUserToDepartmentRequest
	(*AssignUserToDepartmentResponse)(nil), // 18: absence.v1.AssignUserToDepartmentResponse
	(*AssignUserToTeamRequest)(nil),        // 19: absence.v1.AssignUserToTeamRequest
	(*AssignUserToTeamResponse)(nil),       // 20: absence.v1.AssignUserToTeamResponse
	(*UpdateUserRequest)(nil),              // 21: absence.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),             // 22: absence.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),              // 23: absence.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),             // 24: absence.v1.DeleteUserResponse
	(*CreateDepartmentRequest)(nil),        // 25: absence.v1.CreateDepartmentRequest
	(*CreateDepartmentResponse)(nil),       // 26: absence.v1.CreateDepartmentResponse
	(*GetDepartmentsRequest)(nil),          // 27: absence.v1.GetDepartmentsRequest
	(*GetDepartmentsResponse)(nil),         // 28: absence.v1.GetDepartmentsResponse
	(*UpdateDepartmentRequest)(nil),        // 29: absence.v1.UpdateDepartmentRequest
	(*UpdateDepartmentResponse)(nil),       // 30: absence.v1.UpdateDepartmentResponse
	(*DeleteDepartmentRequest)(nil),        // 31: absence.v1.DeleteDepartmentRequest
	(*DeleteDepartmentResponse)(nil),       // 32: absence.v1.DeleteDepartmentResponse
	(*CreateTeamRequest)(nil),              // 33: absence.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),             // 34: absence.v1.CreateTeamResponse
	(*GetTeamsRequest)(nil),                // 35: absence.v1.GetTeamsRequest
	(*GetTeamsResponse)(nil),               // 36: absence.v1.GetTeamsResponse
	(*UpdateTeamRequest)(nil),              // 37: absence.v1.UpdateTeamRequest
	(*UpdateTeamResponse)(nil),             // 38: absence.v1.UpdateTeamResponse
	(*DeleteTeamRequest)(nil),              // 39: absence.v1.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),             // 40: absence.v1.DeleteTeamResponse
	(*CreateHolidayRequest)(nil),           // 41: absence.v1.CreateHolidayRequest
	(*CreateHolidayResponse)(nil),          // 42: absence.v1.CreateHolidayResponse
	(*GetHolidaysRequest)(nil),             // 43: absence.v1.GetHolidaysRequest
	(*GetHolidaysResponse)(nil),            // 44: absence.v1.GetHolidaysResponse
	(*UpdateHolidayRequest)(nil),           // 45: absence.v1.UpdateHolidayRequest
	(*UpdateHolidayResponse)(nil),          // 46: absence.v1.UpdateHolidayResponse
	(*DeleteHolidayRequest)(nil),           // 47: absence.v1.DeleteHolidayRequest
	(*DeleteHolidayResponse)(nil),          // 48: absence.v1.DeleteHolidayResponse
	(*ImportHolidaysRequest)(nil),          // 49: absence.v1.ImportHolidaysRequest
	(*ImportHolidaysResponse)(nil),         // 50: absence.v1.ImportHolidaysResponse
	(*timestamppb.Timestamp)(nil),          // 51: google.protobuf.Timestamp
}
var file_absence_v1_absence_proto_depIdxs = []int32{
	51, // 0: absence.v1.Absence.start_date:type_name -> google.protobuf.Timestamp
	51, // 1: absence.v1.Absence.end_date:type_name -> google.protobuf.Timestamp
	51, // 2: absence.v1.CreateAbsenceRequest.start_date:type_name -> google.protobuf.Timestamp
	51, // 3: absence.v1.CreateAbsenceRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 4: absence.v1.CreateAbsenceResponse.absence:type_name -> absence.v1.Absence
	51, // 5: absence.v1.GetAbsencesRequest.start_date:type_name -> google.protobuf.Timestamp
	51, // 6: absence.v1.GetAbsencesRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 7: absence.v1.GetAbsencesResponse.absences:type_name -> absence.v1.Absence
	51, // 8: absence.v1.UpdateAbsenceRequest.start_date:type_name -> google.protobuf.Timestamp
	51, // 9: absence.v1.UpdateAbsenceRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 10: absence.v1.UpdateAbsenceResponse.absence:type_name -> absence.v1.Absence
	1,  // 11: absence.v1.CreateUserResponse.user:type_name -> absence.v1.User
	1,  // 12: absence.v1.GetUsersResponse.users:type_name -> absence.v1.User
	1,  // 13: absence.v1.AssignUserToDepartmentResponse.user:type_name -> absence.v1.User
	1,  // 14: absence.v1.AssignUserToTeamResponse.user:type_name -> absence.v1.User
	1,  // 15: absence.v1.UpdateUserResponse.user:type_name -> absence.v1.User
	2,  // 16: absence.v1.CreateDepartmentResponse.department:type_name -> absence.v1.Department
	2,  // 17: absence.v1.GetDepartmentsResponse.departments:type_name -> absence.v1.Department
	2,  // 18: absence.v1.UpdateDepartmentResponse.department:type_name -> absence.v1.Department
	3,  // 19: absence.v1.CreateTeamResponse.team:type_name -> absence.v1.Team
	3,  // 20: absence.v1.GetTeamsResponse.teams:type_name -> absence.v1.Team
	3,  // 21: absence.v1.UpdateTeamResponse.team:type_name -> absence.v1.Team
	4,  // 22: absence.v1.CreateHolidayResponse.holiday:type_name -> absence.v1.Holiday
	4,  // 23: absence.v1.GetHolidaysResponse.holidays:type_name -> absence.v1.Holiday
	4,  // 24: absence.v1.UpdateHolidayResponse.holiday:type_name -> absence.v1.Holiday
	41, // 25: absence.v1.ImportHolidaysRequest.holidays:type_name -> absence.v1.CreateHolidayRequest
	5,  // 26: absence.v1.AbsenceService.CreateAbsence:input_type -> absence.v1.CreateAbsenceRequest
	7,  // 27: absence.v1.AbsenceService.GetAbsences:input_type -> absence.v1.GetAbsencesRequest
	9,  // 28: absence.v1.AbsenceService.UpdateAbsence:input_type -> absence.v1.UpdateAbsenceRequest
	11, // 29: absence.v1.AbsenceService.DeleteAbsence:input_type -> absence.v1.DeleteAbsenceRequest
	13, // 30: absence.v1.UserService.CreateUser:input_type -> absence.v1.CreateUserRequest
	15, // 31: absence.v1.UserService.GetUsers:input_type -> absence.v1.GetUsersRequest
	17, // 32: absence.v1.UserService.AssignUserToDepartment:input_type -> absence.v1.AssignUserToDepartmentRequest
	19, // 33: absence.v1.UserService.AssignUserToTeam:input_type -> absence.v1.AssignUserToTeamRequest
	21, // 34: absence.v1.UserService.UpdateUser:input_type -> absence.v1.UpdateUserRequest
	23, // 35: absence.v1.UserService.DeleteUser:input_type -> absence.v1.DeleteUserRequest
	25, // 36: absence.v1.OrganizationService.CreateDepartment:input_type -> absence.v1.CreateDepartmentRequest
	27, // 37: absence.v1.OrganizationService.GetDepartments:input_type -> absence.v1.GetDepartmentsRequest
	33, // 38: absence.v1.OrganizationService.CreateTeam:input_type -> absence.v1.CreateTeamRequest
	35, // 39: absence.v1.OrganizationService.GetTeams:input_type -> absence.v1.GetTeamsRequest
	29, // 40: absence.v1.OrganizationService.UpdateDepartment:input_type -> absence.v1.UpdateDepartmentRequest
	31, // 41: absence.v1.OrganizationService.DeleteDepartment:input_type -> absence.v1.DeleteDepartmentRequest
	37, // 42: absence.v1.OrganizationService.UpdateTeam:input_type -> absence.v1.UpdateTeamRequest
	39, // 43: absence.v1.OrganizationService.DeleteTeam:input_type -> absence.v1.DeleteTeamRequest
	41, // 44: absence.v1.HolidayService.CreateHoliday:input_type -> absence.v1.CreateHolidayRequest
	43, // 45: absence.v1.HolidayService.GetHolidays:input_type -> absence.v1.GetHolidaysRequest
	45, // 46: absence.v1.HolidayService.UpdateHoliday:input_type -> absence.v1.UpdateHolidayRequest
	47, // 47: absence.v1.HolidayService.DeleteHoliday:input_type -> absence.v1.DeleteHolidayRequest
	49, // 48: absence.v1.HolidayService.ImportHolidays:input_type -> absence.v1.ImportHolidaysRequest
	6,  // 49: absence.v1.AbsenceService.CreateAbsence:output_type -> absence.v1.CreateAbsenceResponse
	8,  // 50: absence.v1.AbsenceService.GetAbsences:output_type -> absence.v1.GetAbsencesResponse
	10, // 51: absence.v1.AbsenceService.UpdateAbsence:output_type -> absence.v1.UpdateAbsenceResponse
	12, // 52: absence.v1.AbsenceService.DeleteAbsence:output_type -> absence.v1.DeleteAbsenceResponse
	14, // 53: absence.v1.UserService.CreateUser:output_type -> absence.v1.CreateUserResponse
	16, // 54: absence.v1.UserService.GetUsers:output_type -> absence.v1.GetUsersResponse
	18, // 55: absence.v1.UserService.AssignUserToDepartment:output_type -> absence.v1.AssignUserToDepartmentResponse
	20, // 56: absence.v1.UserService.AssignUserToTeam:output_type -> absence.v1.AssignUserToTeamResponse
	22, // 57: absence.v1.UserService.UpdateUser:output_type -> absence.v1.UpdateUserResponse
	24, // 58: absence.v1.UserService.DeleteUser:output_type -> absence.v1.DeleteUserResponse
	26, // 59: absence.v1.OrganizationService.CreateDepartment:output_type -> absence.v1.CreateDepartmentResponse
	28, // 60: absence.v1.OrganizationService.GetDepartments:output_type -> absence.v1.GetDepartmentsResponse
	34, // 61: absence.v1.OrganizationService.CreateTeam:output_type -> absence.v1.CreateTeamResponse
	36, // 62: absence.v1.OrganizationService.GetTeams:output_type -> absence.v1.GetTeamsResponse
	30, // 63: absence.v1.OrganizationService.UpdateDepartment:output_type -> absence.v1.UpdateDepartmentResponse
	32, // 64: absence.v1.OrganizationService.DeleteDepartment:output_type -> absence.v1.DeleteDepartmentResponse
	38, // 65: absence.v1.OrganizationService.UpdateTeam:output_type -> absence.v1.UpdateTeamResponse
	40, // 66: absence.v1.OrganizationService.DeleteTeam:output_type -> absence.v1.DeleteTeamResponse
	42, // 67: absence.v1.HolidayService.CreateHoliday:output_type -> absence.v1.CreateHolidayResponse
	44, // 68: absence.v1.HolidayService.GetHolidays:output_type -> absence.v1.GetHolidaysResponse
	46, // 69: absence.v1.HolidayService.UpdateHoliday:output_type -> absence.v1.UpdateHolidayResponse
	48, // 70: absence.v1.HolidayService.DeleteHoliday:output_type -> absence.v1.DeleteHolidayResponse
	50, // 71: absence.v1.HolidayService.ImportHolidays:output_type -> absence.v1.ImportHolidaysResponse
	49, // [49:72] is the sub-list for method output_type
	26, // [26:49] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_absence_v1_absence_proto_init() }
func file_absence_v1_absence_proto_init() {
	if File_absence_v1_absence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_absence_v1_absence_proto_rawDesc), len(file_absence_v1_absence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   51,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_absence_v1_absence_proto_goTypes,
		DependencyIndexes: file_absence_v1_absence_proto_depIdxs,
		MessageInfos:      file_absence_v1_absence_proto_msgTypes,
	}.Build()
	File_absence_v1_absence_proto = out.File
	file_absence_v1_absence_proto_goTypes = nil
	file_absence_v1_absence_proto_depIdxs = nil
}
