name: Protobuf Lint

on: 
  pull_request:
    paths:
    - .github/workflows/protobuf.yml
    - proto/**
jobs:
  linting:
    name: Buf lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    # Install the `buf` CLI
    - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0
    # Lint your Protobuf sources
    - uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1.1.1
