name: Protobuf Lint

on:
  pull_request:
    paths:
      - .github/workflows/protobuf.yml
      - backend/proto/**
jobs:
  linting:
    name: Buf lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    # Lint your Protobuf sources
    - uses: bufbuild/buf-action@v1
      with:
        input: backend
