name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get tag name
        id: tag
        uses: haya14busa/action-cond@94f77f7a80cd666cb3155084e428254fea4281fd # v1.2.1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      - id: version_tag
        run: |
          echo "::set-output name=tag::$(echo ${{steps.tag.outputs.value}} | cut -d'v' -f2 )"
          echo "::set-output name=tag_chart::$(echo ${{steps.tag.outputs.value}} | cut -d'v' -f2 )"


      #Update version in Chart.yaml
      - if: steps.tag.outputs.value != ''
        run: |
          sed -i '/^version:/c\version: ${{steps.version_tag.outputs.tag_chart}}' ./helm/offly/Chart.yaml
          sed -i '/^appVersion:/c\appVersion: "${{steps.version_tag.outputs.tag_chart}}"' ./helm/offly/Chart.yaml

      - if: steps.tag.outputs.value != ''
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "ci: bump charts to ${{steps.version_tag.outputs.tag}}"
          branch: main
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            bananaops/offly:latest
            bananaops/offly:${{steps.version_tag.outputs.tag}}
          build-args: |
            VERSION=${{steps.version_tag.outputs.tag}}
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}
            VITE_API_URL=/api/v1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  release-helm: 
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
  
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
